### PR TITLE
Add index to optimize for list task executions for node execution

### PR DESCRIPTION
**Pull request by katrogan**
# TL;DR
Add index to optimize for list task executions for node execution

## Type
 - [x] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [x] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Tracking Issue
https://github.com/lyft/flyte/issues/328

## Follow-up issue
_NA_

### CODE REVIEW

**Comment by anandswaminathan** [comment]
@katrogan The gorm joins are fine? Has the latency gone down completely?

**Comment by wild-endeavor** [comment]
What happens when you try this locally?  Do you see a performance bump?

Ideally, I feel like this is a gorm issue rather than a postgres issue, is there no way to skip those tables when not necessary?  The query that gorm is delivering to postgres has the tables right?

**Comment by katrogan** [comment]
@anandswaminathan yeah, i'm seeing latency on the order of formerly seconds to 0.1 ms now

**Comment by katrogan** [comment]
@wild-endeavor I was misguided in the original reference bug - the query optimizer does indeed handle eliding the joins. adding this index improved query performance significantly

**Comment by wild-endeavor** [comment]
+1

**Pull request merged**
