### PR TITLE
Add index prefix to model declaration

### PR DESCRIPTION
**Pull request by honnix**
# TL;DR
Fix indices for a few models.

## Type
 - [x] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [x] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
Added `index` prefix according to https://gorm.io/docs/indexes.html.

## Tracking Issue
https://github.com/lyft/flyte/issues/570

## Follow-up issue
_NA_

### CODE REVIEW

**Comment by honnix** [comment]
Hmm, it is not obvious why e2e failed...

**Comment by honnix** [comment]
@kumare3 Could you please take a look?

**Review by katrogan — APPROVED** [review]

**Comment by honnix** [comment]
@katrogan Thanks for approving the PR. Is the e2e test a known issue?

**Comment by katrogan** [comment]
I want to say yes, see https://github.com/lyft/flyteadmin/pull/132#issuecomment-716827614

has end2end been passing for you on open PRs previously?

**Comment by honnix** [comment]
https://github.com/lyft/flyteadmin/actions/runs/307331872 this one passed, but it wasn't my PR. I'm not working on a fork, so it seems to be something different.

**Comment by honnix** [comment]
Looks like the test took too long and got timeout terminated with 124 exit code.

**Comment by honnix** [comment]
I guess killed by timeout here https://github.com/lyft/flyte/blob/master/end2end/execute.sh#L50

**Comment by honnix** [comment]
Tried https://github.com/lyft/flyte/pull/571 and seems it is just slow. Maybe too weak machine?

**Pull request merged**
